static const char *RcsId = "$Header: /home/cvsadm/cvsroot/fermi/servers/replicator/src/ClassFactory.cpp,v 1.1.1.1 2009-12-09 13:24:29 mdm Exp $";
//+=============================================================================
//
// file :        ClassFactory.cpp
//
// description : C++ source for the class_factory method of the DServer
//               device class. This method is responsible to create
//               all class singletin for a device server. It is called
//               at device server startup
//
// project :     TANGO Device Server
//
// $Author: mdm $
//
// $Revision: 1.1.1.1 $
//
// $Log: ClassFactory.cpp,v $
// Revision 1.1.1.1  2009-12-09 13:24:29  mdm
// first import
//
//
// copyleft :    European Synchrotron Radiation Facility
//               BP 220, Grenoble 38043
//               FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================


#include <tango.h>
#include <ReplicatorClass.h>

/**
 *	Create ReplicatorClass singleton and store it in DServer object.
 */

void Tango::DServer::class_factory()
{

	add_class(Replicator_ns::ReplicatorClass::init("Replicator"));

}
