static const char *RcsId =
        "$Header: /home/cvsadm/cvsroot/fermi/servers/replicator/src/ReplicatorStateMachine.cpp,v 1.2 2019-03-18 16:38:32 claudio Exp $";
//+=============================================================================
//
// file :         ReplicatorStateMachine.cpp
//
// description :  C++ source for the Replicator and its alowed. 
//                method for commands and attributes
//
// project :      TANGO Device Server
//
// $Author: claudio $
//
// $Revision: 1.2 $
//
// $Log: ReplicatorStateMachine.cpp,v $
// Revision 1.2  2019-03-18 16:38:32  claudio
// first successful propagation of ATTR_CONF_EVENT
//
// Revision 1.1.1.1  2009-12-09 13:24:29  mdm
// first import
//
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#include <tango.h>
#include <Replicator.h>
#include <ReplicatorClass.h>

/*====================================================================
 *	This file contains the methods to allow commands and attributes
 * read or write execution.
 *
 * If you wand to add your own code, add it between 
 * the "End/Re-Start of Generated Code" comments.
 *
 * If you want, you can also add your own methods.
 *====================================================================
 */

namespace Replicator_ns {

//=================================================
//		Attributes Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		Replicator::is_GenericScalar_allowed
// 
// description : 	Read/Write allowed for GenericScalar attribute.
//
//-----------------------------------------------------------------------------
bool Replicator::is_GenericScalar_allowed(Tango::AttReqType type) {
    //	End of Generated Code

    //	Re-Start of Generated Code
    return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Replicator::is_GenericSpectrum_allowed
// 
// description : 	Read/Write allowed for GenericSpectrum attribute.
//
//-----------------------------------------------------------------------------
bool Replicator::is_GenericSpectrum_allowed(Tango::AttReqType type) {
    //	End of Generated Code

    //	Re-Start of Generated Code
    return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Replicator::is_GenericImage_allowed
// 
// description : 	Read/Write allowed for GenericImage attribute.
//
//-----------------------------------------------------------------------------
bool Replicator::is_GenericImage_allowed(Tango::AttReqType type) {
    //	End of Generated Code

    //	Re-Start of Generated Code
    return true;
}
//+----------------------------------------------------------------------------
//
// method :             Test::is_RState_allowed
//
// description :        Read/Write allowed for RState attribute.
//
//-----------------------------------------------------------------------------
bool Replicator::is_RState_allowed(Tango::AttReqType type) {
    //      End of Generated Code
    //      Re-Start of Generated Code
    return true;
}
//+----------------------------------------------------------------------------
//
// method :             Test::is_RStatus_allowed
//
// description :        Read/Write allowed for RStatus attribute.
//
//-----------------------------------------------------------------------------
bool Replicator::is_RStatus_allowed(Tango::AttReqType type) {
    //      End of Generated Code
    //      Re-Start of Generated Code
    return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		Replicator::is_GenericCommand_allowed
// 
// description : 	Execution allowed for GenericCommand command.
//
//-----------------------------------------------------------------------------
bool Replicator::is_GenericCommand_allowed(const CORBA::Any &any) {
    //	End of Generated Code

    //	Re-Start of Generated Code
    return true;
}

}	// namespace Replicator_ns
